spring:
  output:
    ansi:
      enabled: always
  devtools:
    restart:
      enabled: true
  datasource:
    url: jdbc:mysql://localhost:3306/store_api?createDatabaseIfNotExist=true
    username: root
    password: admin
  jpa:
    show-sql: true
  thymeleaf:
    check-template-location: false
websiteUrl: http://localhost:4242